project:
  type: website
  output-dir: docs

website:
  title: "Contents"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "ESC"
        contents:
          - UsingESCSiteData.qmd
          - UsingESCTreeResults.qmd
          - UsingESCTreeModel.qmd
          - UsingESCWCC.qmd

format:
  html:
    embed-resources: true
    theme: light
    code-copy: true
    fontsize: 1rem
    fontcolor: "#000000"
    linkcolor: "#2943d6"
    monofont: courier new
    backgroundcolor: "#ffffff"
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left
    smooth-scroll: true
    grid:
      sidebar-width: 500px
      # body-width: 1400px